apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-service
  template:
    metadata:
      labels:
        app: inventario-service
    spec:
      containers:
        - name: inventario-service
          image: yourdockerhub/inventario-service:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: inventario-config
            - secretRef:
                name: inventario-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 15